### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by nikophil** [dmishh/SettingsBundle#101]
Hi,

thanks for this nice bundle.

could you provide a symfony 4 support please ?

thanks

**Comment by Nyholm** [comment]
Hey. 

That is a great idea. What are the steps for this bundle to go to Symfony 4?

**Comment by nikophil** [comment]
I think it is already compatible with sf4, it just needs some composer.json updates and some flex recipes

**Comment by Nyholm** [comment]
Great. Could you add a PR for our composer.json and add a flex recipe? I would be happy to merge them both

**Comment by nikophil** [comment]
okay, i'll try do to it today

**Comment by Nyholm** [comment]
Excellent

**Comment by glennthehuman** [comment]
Hello. May I know if anyone is actively working on this?

**Comment by anacona16** [comment]
I'm using this bundle with Symfony 4.3

**Comment by link365dev** [comment]
@anacona16 What steps did you do? I tried _composer require_ but it didn't go through.

**Comment by anacona16** [comment]
I'm using a fork of this bundle, this fork is compatible with SF 4 https://github.com/nikophil/SettingsBundle.git

To use it you should add a new entry in you composer.json file:

```json
     "repositories": [
        {
            "type":"package",
            "package": {
                "name": "dmishh/settings-bundle",
                "version": "dev-master",
                "source": {
                    "url": "https://github.com/nikophil/SettingsBundle.git",
                    "type": "git",
                    "reference": "symfony-4-support"
                }
            }
        }
    ],
```

Then in the autoload entry you should add a new line:

```json
     "autoload": {
        "psr-4": {
            "App\\": "src/",
            "Dmishh\\SettingsBundle\\": "vendor/dmishh/settings-bundle/"
        }
    },
```

The run composer and it will work.

**Comment by Nyholm** [comment]
Fixed in master. 
I will tag a release later today.
