### ISSUE TITLE
What should SettingManager::all return?

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#16]
As the topic suggest, what should be returned on all? (A) All settings that the users have stored or (B) All settings that the user can store?

Scenario A: 
```php 
$sm=$this->get('settings_manager');
$sm->all(); // array('all_scope_setting'=>null)
$sm->all($this->getUser()); // array()  /* difference */

$sm->set('all_scope_setting', 'value');
$sm->all(); // array('all_scope_setting'=>'value')
$sm->all($this->getUser()); // array() /* difference */

$sm->set('all_scope_setting', 'foobar', $this->getUser());
$sm->all(); // array('all_scope_setting'=>'value')
$sm->all($this->getUser()); // array('all_scope_setting'=>'foobar')
```

Scenario B: 
```php 
$sm=$this->get('settings_manager');
$sm->all(); // array('all_scope_setting'=>null)
$sm->all($this->getUser()); // array('all_scope_setting'=>null)  /* difference */

$sm->set('all_scope_setting', 'value');
$sm->all(); // array('all_scope_setting'=>'value')
$sm->all($this->getUser()); // array('all_scope_setting'=>'value')  /* difference */

$sm->set('all_scope_setting', 'foobar', $this->getUser());
$sm->all(); // array('all_scope_setting'=>'value')
$sm->all($this->getUser()); // array('all_scope_setting'=>'foobar')
```

At the moment is A implemented. I suggest we should implement B instead because it make more sense. Especially with #15.

**Comment by dmishh** [comment]
Absolutely :+1:

**Comment by Nyholm** [comment]
Solving this issue will also (like #10) be a BC break.

**Comment by dmishh** [comment]
Let's do this and I'll start 2.x

**Comment by Nyholm** [comment]
I suggest to create a new 1.x branch and continue the work on 2.x in master. I will happily implement a solution to this issue and the cache issue (#8) as soon as #10 is merged. It will be too many merge conflicts otherwise... 

(It's 3 PRs that will do a lot of work on the same class.)

**Comment by dmishh** [comment]
:+1:
Sure, I'll setup the branch for 1.0 today
