### ISSUE TITLE
Rewrite the message in WrongScopeException

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#24]
We should rewrite the `WrongScopeException` to something more descriptive. Ie there are two reasons for the `WrongScopeException` to be thrown. 

1. You have misconfigured the scope
2. You have called the `SettingsManager::get` with the wrong amount of parameters. Either you forgot the $owner on `Local` scope or you used $owner on a `Global` scope.

**Comment by dmishh** [comment]
Did you mean splitting `WrongScopeException` into two exceptions that will cover two options you mentioned?

**Comment by Nyholm** [comment]
I don't think it's possible for us to know what the reason for the error is. I just want the exception message to be more descriptive about what could have caused the exception to be thrown. So my suggestion is purely to rewrite the message.

**Comment by dmishh** [comment]
Ah, I've got it. How about `ScopeLogicException` ?

**Comment by Nyholm** [comment]
Checkout #32
