### ISSUE TITLE
database schema for clean install

### ISSUE THREAD

**Issue by metalmini** [dmishh/SettingsBundle#34]
Hi guys,

I am trying to install this bundle in my project but when i create a new database and run  `doctrine:schema:create` i get the following error:
 ` There is no column with name 'ownerId' on table 'dmishh_settings'.  `
Any idea what could be causing this?

**Comment by dmishh** [comment]
Hi, @metalmini. Thanks for the report.
I'll check this soon

**Comment by metalmini** [comment]
I just installed version 1 and this seems to be working just fine. But if i update to the latest it throws the same error. Composer.json contains `"dmishh/settings-bundle": "2.0.*@dev"`

**Comment by Nyholm** [comment]
I tried to reproduce the error but a could not. Im using Doctrine 2.5 and Symfony 2.7 with MySQL 5.6 on OSX. 

Will this patch help? https://github.com/dmishh/SettingsBundle/commit/5478543fecfe16b2938b806755f6c94db45521a8

**Comment by dmishh** [comment]
@metalmini Any updates? Can you reproduce the issue on the current state of the `master` branch?

**Comment by dmishh** [comment]
Considering this as resolved
