### ISSUE TITLE
Template override via Bundle

### ISSUE THREAD

**Issue by rvanlaak** [dmishh/SettingsBundle#37]
You mention overriding the layout and manage Twig file [in your readme](https://github.com/dmishh/SettingsBundle#overriding-layout), but I think this can easily be done by using [Symfony's default Bundle inheritance](http://symfony.com/doc/current/cookbook/bundles/inheritance.html#overriding-resources-templates-routing-etc).

Copying `layout.html.twig` to `app/Resources/DmishhSettingsBundle/views` will allow users to override it without having to define it in the config. :+1:

**Comment by dmishh** [comment]
What if you want to use your existing layout without copying it to the `app/Resources/DmishhSettingsBundle/views` folder?

**Comment by Rvanlaak** [comment]
Let `/app/Resources/DmishhSettingsBundle/views/layout.html.twig` extend your existing layout, and put the `{% block settings_form %}{% endblock %}` in your default block. Maybe the block can be renamed to `content` to make the block's name more consistent with other bundles.

**Comment by dmishh** [comment]
@rvanlaak @Nyholm hi guys. I really don't have time to support this bundle, but I don't want to just bury it. I would like to transfer the bundle to one of you, since you've been the most active contributors. Of course if you want to.

**Comment by Nyholm** [comment]
Lets both do it. I've been reading all issues and PRs for a year now. 
@rvanlaak Do you want to join forces and make sure 2.0 is released?

**Comment by dmishh** [comment]
Ok, I'll give you guys push access.

**Comment by dmishh** [comment]
Done @Nyholm @rvanlaak

**Comment by rvanlaak** [comment]
Would be great! :rocket: How is sf3.0 compatibility? Otherwise I'll focus on that.

**Comment by Nyholm** [comment]
@rvanlaak: Will you send a PR?

**Comment by rvanlaak** [comment]
Do you want me to get rid of the `settings_manager.layout` parameter? It is solely used by the `SettingController:108`. Think we should always advocate for the bundle inheritance.

**Comment by Nyholm** [comment]
Yeah. Lets follow the Symfony best practices. Only inheritance will be fine.
