### ISSUE TITLE
[Insight] Projects must not depend on dependencies with known security issues

### ISSUE THREAD

**Issue by jewome62** [dmishh/SettingsBundle#45]
> The checker detected 1 security issues in package doctrine/orm installed in version 2.4.7.0 1) Security Misconfiguration Vulnerability in various Doctrine projects.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5375684f-5b40-489a-aca5-eb01c3ca5ac2/analyses/24)_

**Comment by Nyholm** [comment]
I have a PR ready that will fix this. Just waiting on #53 to be merged.

**Comment by Nyholm** [comment]
This is fixed by #58
