### ISSUE TITLE
2.8 / 3.0 Compatibily ?

### ISSUE THREAD

**Issue by Atyz** [dmishh/SettingsBundle#50]
List of TODOs for `~2.8|~3.0` compatibility:

- [x] Twig `SettingExtension` deprecations
- [x] Decide on bumping `framework-bundle` from `2.3 LTS` to `2.6` or `2.7 LTS`
- [x] Service definition factory method #62 
- [ ] `FormType::getName`, `FormType::setDefaultOptions`, buildForm via FormType FQCN

**Comment by rvanlaak** [comment]
@dmishh [the `factory_method` is deprecated](https://github.com/dmishh/SettingsBundle/blob/master/src/Dmishh/Bundle/SettingsBundle/Resources/config/services.yml#L22), so hope that can be fixed.

**Comment by Nyholm** [comment]
Can you provide a TODO on what to be done before this issue is resolved?

**Comment by rvanlaak** [comment]
@Nyholm added TODO list to issue description

**Comment by Nyholm** [comment]
I've created #71, #72 and #73
