### ISSUE TITLE
Code standards

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#61]
I would suggest to follow Symfony best practices with coding standards. That means PSR-1 and PSR-2 + some extra Symfony stuff. 

Any thoughts?

**Comment by rvanlaak** [comment]
:+1: to me, but you want to add this in `CONTRIBUTE.md` or another file? Bundle already looks quite PSR-2 to me.

**Comment by Nyholm** [comment]
I though about minor fixes like #68
