### ISSUE TITLE
PHP 5.4 & 5.5 -support.

### ISSUE THREAD

**Issue by jounisuo** [dmishh/SettingsBundle#75]
Wouldn't it make sense to support 5.4 as the 2.8 -branch of framework-bundle
( https://github.com/symfony/framework-bundle/blob/2.8/composer.json ) supports >=5.3.9? As does Symfony 2.8. Doctrine 2.5 supports >5.4, so why require php 5.6, when some servers might still be on 5.4?

**Comment by Nyholm** [comment]
This is a very opinionated question. The counter argument is: 
Would it make sense to support a PHP version that is **not officially supported**? Why should we bother if not event the core team bothers?

Do you have a reson why you need PHP 5.4 support?

**Comment by jounisuo** [comment]
The long term support version of symfony supports >=5.3.9 http://symfony.com/doc/2.8/reference/requirements.html 
Centos 7 (It's quite popular) only comes with 5.4.

**Comment by rvanlaak** [comment]
As a bundle we should always consider whether BC compatibility does not stale development of new features, like supporting the Symfony `3.0` branch. Some of the features, like the use of a FQCN to define form types, are a hard BC break that would require the maintainers of all bundles to bump their php requirement. 

@Nyholm think we should at least update the `1.x` branch to https://github.com/dmishh/SettingsBundle/commit/a1747348665f69213cd962de27cbcd1ab29b1c4d and release the latest stable tag of that. You see any possible bugs between March 9 (when v1.0.7 was released) and that commit I mentioned?

**Comment by rvanlaak** [comment]
Think

**Comment by Nyholm** [comment]
Sure. Lets!

**Comment by rvanlaak** [comment]
`2.0.0-beta2` has been released, I've updated `UPGRADE.md` accordingly.
