### ISSUE TITLE
Exception on new Cache interface

### ISSUE THREAD

**Issue by rvanlaak** [dmishh/SettingsBundle#79]
When we build the new cached container, we get the following exception:

> Catchable Fatal Error: Argument 2 passed to Dmishh\SettingsBundle\Manager\CachedSettingsManager::__construct() must be an instance of Psr\Cache\CacheItemPoolInterface, instance of Doctrine\Common\Cache\ApcCache given

The cache service we inject right now is defined via `doctrine_cache`:
```
dmishh_settings:
    cache_service: my_apc_cache
    cache_lifetime: 3600
```  
```yml
doctrine_cache:
    providers:
        my_apc_cache:
            type: apc
            namespace: my_apc
```
See https://github.com/dmishh/SettingsBundle/blob/master/Resources/doc/advanced-configuration.md

@Nyholm  [The caching layer has changed](https://github.com/dmishh/SettingsBundle/blob/master/Resources/doc/advanced-configuration.md#caching), so can you also add some docs to `UPGRADE.md` about that?

Do you think we should make the `Doctrine\Common\Cache` that was supported before compatible with the new `Psr\Cache\CacheItemPoolInterface` that is used now? Or will Doctrine eventually also move to PSR? That would mean everybody has to require https://github.com/php-cache/adapter-bundle right?

**Comment by Nyholm** [comment]
Yes, we should update the upgrade docs. 

The doctrine cache should not be used any more. I do also know that Doctrine has no plans to go PSR6. 

> Do you think we should make the Doctrine\Common\Cache that was supported before compatible with the new Psr\Cache\CacheItemPoolInterface that is used now?

No, not in this case. There is a [bridge](https://github.com/php-cache/doctrine-bridge) btw but there is nothing we should use. 

> That would mean everybody has to require https://github.com/php-cache/adapter-bundle right?

No, it is not a requirement. But it will make everything a lot easier if you use that bundle. Read about it here: http://www.php-cache.com/en/latest/symfony/adapter-bundle/

**Comment by rvanlaak** [comment]
Did dive into the adapter bundle and factories a bit, and like the way it's implemented :+1: I'm fine with upgrading to PSR as much as possible, took me 10 minutes to figure out about requiring the additional adapters and changing the config. Basically this is a nice way to push your adapter bundle to the masses right? :wink: 

Oh, didn't see a 'issues' tab in the adapter repository. What about adding datacollectors for the WebProfiler? Maybe by [decorating the adapter](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/DataCollector/LoggerDataCollector.php), and adding [a Twig view](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Collector/logger.html.twig)?

**Comment by Nyholm** [comment]
Thats right =)

We have a shared issue tracker for all the repositories: https://github.com/php-cache/issues/issues

That functionality belongs to the [CacheBundle](https://github.com/php-cache/cache-bundle)

**Comment by rvanlaak** [comment]
@Nyholm the old cache keys collide with the accepted keys in the `CacheBundle` if we do the following:

```php
$tourCount = $this->get('settings_manager')->get('editor_tour_started', $this->getUser(), 0);
```

![dmissh-setting-reserved](https://cloud.githubusercontent.com/assets/2707563/14498547/2a413d1e-019b-11e6-99f9-e52c98f8cf1a.png)

So basically the caching is broken now, the characters from the key we defined are not in the list of reserved characters. Can you take a look at this?
