### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by nexxome** [dmishh/SettingsBundle#89]
I use a filesystem cache service like described in the docs. The problem is, when I change the value of a setting with the CachedSettingsManager set method, the cache with the single setting key (for example dmishh_settings__setting) is cleared, but not the cache that will be filled with the all method (dmishh_settings__).
So when I fetch the settings with $this->get('settings_manager')->all(), I get wrong values from the expired cache.
So maybe this cache should also be deleted in the set methods.

**Comment by Nyholm** [comment]
Thank you @nexxome for the issue. I've created a PR that I think will fix this problem. Can you try it out and confirm?

PR #90

**Comment by nexxome** [comment]
Confirmed, #90  fixes this issue. Thanks!

**Comment by rvanlaak** [comment]
@Nyholm you want me to merge and release a patch version?

**Comment by Nyholm** [comment]
Awesome @nexxome. 

Yes @rvanlaak. I'll make sure the tests passes in that PR and fix the stuff you ask for. :)

**Comment by Nyholm** [comment]
I've just released beta-4
